using System.Collections.Generic;
using System.Windows.Forms;

namespace Titration_Analyzer
{
    public partial class Form1
    {
        class acids
        {
            public string acidname;
            public string acidformula;
            public string acidpKavalues;

            public void acidlookup(string acidlookup)
            {
                {
                    List<string> acidtolookup = new List<string>();
                    List<acids> acid = new List<acids> {
                        new acids { acidname = "Hexafluoroantimonic acid", acidformula = "F6H13O6Sb", acidpKavalues = "-17"},
                        new acids { acidname = "Fluorosulfonic acid", acidformula = "HSO3F", acidpKavalues = "-14"},
                        new acids { acidname = "Hexafluoroarsenic acid", acidformula = "AsH3O4", acidpKavalues = "-13"},
                        new acids { acidname = "Disulfuric acid", acidformula = "H2S2O7", acidpKavalues = "-12"},
                        new acids { acidname = "Chlorosulfonic acid", acidformula = "HSO3Cl", acidpKavalues = "-10.43"},
                        new acids { acidname = "Hydroiodic", acidformula = "HI", acidpKavalues = "-10"},
                        new acids { acidname = "Hexafluorophosphoric Acid", acidformula = "HPF6", acidpKavalues = "-10"},
                        new acids { acidname = "Hydrobromic Acid", acidformula = "HBr", acidpKavalues = "-8.7"},
                        new acids { acidname = "Perchloric Acid", acidformula = "HClO4", acidpKavalues = "-8"},
                        new acids { acidname = "Hydrochloric Acid", acidformula = "HCl", acidpKavalues = "-6.5"},
                        new acids { acidname = "Trifluoromethanesulfonic acid", acidformula = "CF3SO3H", acidpKavalues = "-5.21"},
                        new acids { acidname = "Pentafluoroethanesulfonic acid", acidformula = "C2HF5O3S", acidpKavalues = "-5.1"},
                        new acids { acidname = "Heptafluoropropanesulfonic acid", acidformula = "C3HF7O3S", acidpKavalues = "-5"},
                        new acids { acidname = "Peroxonitric acid", acidformula = "HNO4", acidpKavalues = "-5"},
                        new acids { acidname = "Dichromic acid", acidformula = "CrH2O4", acidpKavalues = "-4.5"},
                        new acids { acidname = "Peroxodisulfuric acid", acidformula = "H2S2O8", acidpKavalues = "-3.5"},
                        new acids { acidname = "Dithionic acid", acidformula = "H2S2O6", acidpKavalues = "-3.4"},
                        new acids { acidname = "Hexafluorosilicic acid", acidformula = "H2SiF6", acidpKavalues = "-3,0.35"},
                        new acids { acidname = "Selenic acid", acidformula = "H2SeO4", acidpKavalues = "-3"},
                        new acids { acidname = "p-Toluenesolfonic Acid", acidformula = "C7H8O3S", acidpKavalues = "-2.8"},
                        new acids { acidname = "Chloric acid", acidformula = "HClO3", acidpKavalues = "-2.7"},
                        new acids { acidname = "Benzenesulfonic acid", acidformula = "C6H6O3S", acidpKavalues = "-2.5"},
                        new acids { acidname = "Permanganic acid", acidformula = "HMnO4", acidpKavalues = "-2.25"},
                        new acids { acidname = "Methanesulfonic acid", acidformula = "CH4O3S", acidpKavalues = "-1.92"},
                        new acids { acidname = "Thiocyanic acid", acidformula = "HSCN", acidpKavalues = "-1.85"},
                        new acids { acidname = "2-propanesulfonic acid", acidformula = "C3H8O3S", acidpKavalues = "-1.79"},
                        new acids { acidname = "Butanesulfonic acid", acidformula = "C4H10O3S", acidpKavalues = "-1.68"},
                        new acids { acidname = "Ethanesulfonic acid", acidformula = "C2H6O3S", acidpKavalues = "-1.68"},
                        new acids { acidname = "Difluorophosphoric acid", acidformula = "HPO2F2", acidpKavalues = "-1.5"},
                        new acids { acidname = "1-propanesulfonic acid", acidformula = "C3H8O3S", acidpKavalues = "-1.49"},
                        new acids { acidname = "Octanesulfonic ", acidformula = "C8H18O3S", acidpKavalues = "-1.41"},
                        new acids { acidname = "Nitric acid", acidformula = "HNO3", acidpKavalues = "-1.4"},
                        new acids { acidname = "Isothiocyanic acid", acidformula = "HSCN", acidpKavalues = "-1.28"},
                        new acids { acidname = "Perrhenic acid", acidformula = "HReO4", acidpKavalues = "-1.25"},
                        new acids { acidname = "Chromic acid", acidformula = "H2CrO4", acidpKavalues = "0.74,6.49"},
                        new acids { acidname = "Tetrafluoroboric acid", acidformula = "HBF4", acidpKavalues = "-0.4"},
                        new acids { acidname = "Bromic acid", acidformula = "HBRO3", acidpKavalues = "0"},
                        new acids { acidname = "EDTA", acidformula = "C10H16N2O8", acidpKavalues = "2,2.7,6.16,10.26"},
                        new acids { acidname = "Peroxodiphosphoric", acidformula = "H4P2O8", acidpKavalues = "-3"},
                        new acids { acidname = "Sulfuric", acidformula = "H2SO4", acidpKavalues = "-3"},
                        new acids { acidname = "Potassium Hydroxide", acidformula = "KOH", acidpKavalues = "15.7"},
                        new acids { acidname = "Sodium Hydroxide", acidformula = "NaOH", acidpKavalues = "15.7"},
                        new acids { acidname = "Barium Hydroxide", acidformula = "BaO2H2", acidpKavalues = "13.8,13.36"},
                        new acids { acidname = "Caesium Hydroxide", acidformula = "CsOH", acidpKavalues = "15.8"},
                        new acids { acidname = "Calcium Hydroxide", acidformula = "CaO2H2", acidpKavalues = "12.6,11.57"},
                        new acids { acidname = "Lithium Hydroxide", acidformula = "LiOH", acidpKavalues = "14.04"},
                        new acids { acidname = "Rubidium Hydroxide", acidformula = "RbOH", acidpKavalues = "15.4"},
                        new acids { acidname = "Ammonia", acidformula = "NH3", acidpKavalues = "9.25"},
                        new acids { acidname = "Ammonium Hydroxide", acidformula = "NH4OH", acidpKavalues = "9.25"},
                        new acids { acidname = "Formic acid", acidformula = "CH2O2", acidpKavalues = "3.75"},
                        new acids { acidname = "Methylamine", acidformula = "CH5N", acidpKavalues = "10.63"},
                        new acids { acidname = "Trichloroacetic acid", acidformula = "C2HCl3O2", acidpKavalues = "0.7"},
                        new acids { acidname = "Dichloroacetic acid", acidformula = "C2H2Cl2O2", acidpKavalues = "1.48"},
                        new acids { acidname = "Glyoxylic", acidformula = "C2H2O3", acidpKavalues = "3.18"},
                        new acids { acidname = "Oxalic acid", acidformula = "C2H2O4", acidpKavalues = "1.23,4.19"},
                        new acids { acidname = "Bromoacetic acid", acidformula = "C2H3BrO2", acidpKavalues = "2.69"},
                        new acids { acidname = "Chloroacetic acid", acidformula = "C2H3ClO2", acidpKavalues = "2.85"},
                        new acids { acidname = "Iodoacetic acid", acidformula = "C2H3IO2", acidpKavalues = "3.12"},
                        new acids { acidname = "Thioacetic acid", acidformula = "C2H4OS", acidpKavalues = "3.33"},
                        new acids { acidname = "Acetic acid", acidformula = "C2H4O2", acidpKavalues = "4.76"},
                        new acids { acidname = "Glycolic acid", acidformula = "C2H4O3", acidpKavalues = "3.83"},
                        new acids { acidname = "Ethyleneimine", acidformula = "C2H5N", acidpKavalues = "8.01"},
                        new acids { acidname = "Acetamide", acidformula = "C2H5NO", acidpKavalues = "0.63"},
                        new acids { acidname = "Glycine", acidformula = "C2H5NO2", acidpKavalues = "2.35,9.78"},
                        new acids { acidname = "Ethylene glycol", acidformula = "C2H6O2", acidpKavalues = "14.22"},
                        new acids { acidname = "Cacodylic acid", acidformula = "C2H7AsO2", acidpKavalues = "1.57,6.27"},
                        new acids { acidname = "Dimethylamine", acidformula = "C2H7N", acidpKavalues = "10.68"},
                        new acids { acidname = "Ethylamine", acidformula = "C2H7N", acidpKavalues = "10.7"},
                        new acids { acidname = "Ethanolamine", acidformula = "C2H7NO", acidpKavalues = "9.5"},
                        new acids { acidname = "Taurine", acidformula = "C2H7NO3S", acidpKavalues = "1.5,9.061"},
                        new acids { acidname = "Cysteamine", acidformula = "C2H7NS", acidpKavalues = "8.35,10.81"},
                        new acids { acidname = "1,2-Ethanediamine", acidformula = "C2H8N2", acidpKavalues = "10.712,7.564"},
                        new acids { acidname = "Cyanoacetic acid", acidformula = "C3H3NO2", acidpKavalues = "2.45"},
                        new acids { acidname = "Thiazole", acidformula = "C3H3NS", acidpKavalues = "2.44"},
                        new acids { acidname = "1H-Imidazole", acidformula = "C3H4N2", acidpKavalues = "6.953"},
                        new acids { acidname = "2-Thiazolamine", acidformula = "C3H4N2S", acidpKavalues = "5.36"},
                        new acids { acidname = "Acrylic acid", acidformula = "C3H4O2", acidpKavalues = "4.25"},
                        new acids { acidname = "Pyruvic acid", acidformula = "C3H4O3", acidpKavalues = "2.39"},
                        new acids { acidname = "Malonic acid", acidformula = "C3H4O4", acidpKavalues = "2.83,5.69"},
                        new acids { acidname = "2-Chloropropanoic acid", acidformula = "C3H5ClO2", acidpKavalues = "2.83"},
                        new acids { acidname = "3-Chloropropanoic acid", acidformula = "C3H5ClO2", acidpKavalues = "3.98"},
                        new acids { acidname = "Melamine", acidformula = "C3H6N6", acidpKavalues = "5"},
                        new acids { acidname = "Propanoic acid", acidformula = "C3H6O2", acidpKavalues = "4.86"},
                        new acids { acidname = "3-Hydroxypropanoic acid", acidformula = "C3H6O3", acidpKavalues = "4.51"},
                        new acids { acidname = "Lactic acid", acidformula = "C3H6O3", acidpKavalues = "3.08"},
                        new acids { acidname = "Glyceric acid", acidformula = "C3H6O4", acidpKavalues = "3.52"},
                        new acids { acidname = "Azetidine", acidformula = "C3H7N", acidpKavalues = "11.29"},
                        new acids { acidname = "L-Alanine", acidformula = "C3H7NO2", acidpKavalues = "2.34,9.87"},
                        new acids { acidname = "b-Alanine", acidformula = "C3H7NO2", acidpKavalues = "3.55,10.24"},
                        new acids { acidname = "Methylglycine", acidformula = "C3H7NO2", acidpKavalues = "2.21,10.12"},
                        new acids { acidname = "Cysteine", acidformula = "C3H7NO2S", acidpKavalues = "1.92,8.37,10.7"},
                        new acids { acidname = "Serine", acidformula = "C3H7NO3", acidpKavalues = "2.19,9.21"},
                        new acids { acidname = "l-Cysteic acid", acidformula = "C3H7NO5S", acidpKavalues = "1.3,1.9,8.7"},
                        new acids { acidname = "Glycocyamine", acidformula = "C3H7N3O2", acidpKavalues = "2.82"},
                        new acids { acidname = "Glycerol", acidformula = "C3H8O3", acidpKavalues = "14.15"},
                        new acids { acidname = "Propylamine", acidformula = "C3H9N", acidpKavalues = "10.6"},
                        new acids { acidname = "Trimethylamine", acidformula = "C3H9N", acidpKavalues = "9.8"},
                        new acids { acidname = "1-Amino-2-methoxyethane", acidformula = "C3H9NO", acidpKavalues = "9.89"},
                        new acids { acidname = "Trimethylamine oxide", acidformula = "C3H9NO", acidpKavalues = "4.65"},
                        new acids { acidname = "1,2-Propanediamine", acidformula = "C3H10N2", acidpKavalues = "9.82,6.61"},
                        new acids { acidname = "1,3-Propanediamine", acidformula = "C3H10N2", acidpKavalues = "10.94,9.03"},
                        new acids { acidname = "1,2,3-Triaminopropane", acidformula = "C3H11N3", acidpKavalues = "9.59,7.95"},
                        new acids { acidname = "Pyrazine", acidformula = "C4H4N2", acidpKavalues = "0.65"},
                        new acids { acidname = "Pyridazine", acidformula = "C4H4N2", acidpKavalues = "2.24"},
                        new acids { acidname = "Barbituric acid", acidformula = "C4H4N2O3", acidpKavalues = "4.01"},
                        new acids { acidname = "Alloxanic acid", acidformula = "C4H4N2O5", acidpKavalues = "6.64"},
                        new acids { acidname = "5-Nitropyrimidinamine", acidformula = "C4H4N4O2", acidpKavalues = "0.35"},
                        new acids { acidname = "trans-Fumaric acid", acidformula = "C4H4O4", acidpKavalues = "3.03,4.44"},
                        new acids { acidname = "Maleic acid", acidformula = "C4H4O4", acidpKavalues = "1.83,6.07"},
                        new acids { acidname = "Oxaloacetic acid", acidformula = "C4H4O5", acidpKavalues = "2.22,3.89,13.03"},
                        new acids { acidname = "2-Pyrimidinamine", acidformula = "C4H5N3", acidpKavalues = "3.45"},
                        new acids { acidname = "1-Methylimidazol", acidformula = "C4H6N2", acidpKavalues = "6.95"},
                        new acids { acidname = "Allantoin", acidformula = "C4H6N4O3", acidpKavalues = "8.96"},
                        new acids { acidname = "3-Butenoic acid", acidformula = "C4H6O2", acidpKavalues = "4.34"},
                        new acids { acidname = "trans-Crotonic acid", acidformula = "C4H6O2", acidpKavalues = "4.69"},
                        new acids { acidname = "Acetoacetic acid", acidformula = "C4H6O3", acidpKavalues = "3.58"},
                        new acids { acidname = "2-Oxobutanoic acid", acidformula = "C4H6O3", acidpKavalues = "2.5"},
                        new acids { acidname = "Methymalonic acid", acidformula = "C4H6O4", acidpKavalues = "3.07,5.76"},
                        new acids { acidname = "Succinic acid", acidformula = "C4H6O4", acidpKavalues = "4.16,5.61"},
                        new acids { acidname = "Malic acid", acidformula = "C4H6O5", acidpKavalues = "3.4,5.11"},
                        new acids { acidname = "a-Tartaric acid", acidformula = "C4H6O6", acidpKavalues = "2.98,4.34"},
                        new acids { acidname = "meso-Tartaric acid", acidformula = "C4H6O6", acidpKavalues = "3.22,4.82"},
                        new acids { acidname = "Dihydroxytartaric acid", acidformula = "C4H6O8", acidpKavalues = "1.92"},
                        new acids { acidname = "2-Chlorobutanoic acid", acidformula = "C4H7CIO2", acidpKavalues = "2.86"},
                        new acids { acidname = "3-Chlorobutanoic acid", acidformula = "C4H7CIO2", acidpKavalues = "4.05"},
                        new acids { acidname = "4-Chlorobutanoic acid", acidformula = "C4H7CIO2", acidpKavalues = "4.52"},
                        new acids { acidname = "4-Cyanobutanoic acid", acidformula = "C4H7NO2", acidpKavalues = "2.42"},
                        new acids { acidname = "N-Acetylglycine", acidformula = "C4H7NO3", acidpKavalues = "3.669"},
                        new acids { acidname = "Aspartic acid", acidformula = "C4H7NO4", acidpKavalues = "1.99,3.9,9.9"},
                        new acids { acidname = "Creatinine", acidformula = "C4H7N3O", acidpKavalues = "4.83,9.2"},
                        new acids { acidname = "Asparagine", acidformula = "C4H8N2O3", acidpKavalues = "2.17,8.8"},
                        new acids { acidname = "N-Glycylglycine", acidformula = "C4H8N2O3", acidpKavalues = "3.139"},
                        new acids { acidname = "Butanoic acid", acidformula = "C4H8O2", acidpKavalues = "4.83"},
                        new acids { acidname = "2-Methylpropanoic acid", acidformula = "C4H8O2", acidpKavalues = "4.88"},
                        new acids { acidname = "3-Hydroxybutanoic acid", acidformula = "C4H8O3", acidpKavalues = "4.7"},
                        new acids { acidname = "4-Hydroxybutanoic acid", acidformula = "C4H8O3", acidpKavalues = "4.72"},
                        new acids { acidname = "Pyrrolidine", acidformula = "C4H9N", acidpKavalues = "11.27"},
                        new acids { acidname = "Morpholine", acidformula = "C4H9NO", acidpKavalues = "8.33"},
                        new acids { acidname = "2-Aminobutanoic acid", acidformula = "C4H9NO2", acidpKavalues = "2.29,9.83"},
                        new acids { acidname = "4-Aminobutanoic acid", acidformula = "C4H9NO2", acidpKavalues = "4.031,10.556"},
                        new acids { acidname = "N,N-Dimethylglycine", acidformula = "C4H9NO2", acidpKavalues = "9.89"},
                        new acids { acidname = "2-Methylalanine", acidformula = "C4H9NO2", acidpKavalues = "2.36,10.21"},
                        new acids { acidname = "Homocysteine", acidformula = "C4H9NO2S", acidpKavalues = "2.22,8.87,10.86"},
                        new acids { acidname = "Homoserine", acidformula = "C4H9NO3", acidpKavalues = "2.71,9.62"},
                        new acids { acidname = "DL-Methoxyalanine", acidformula = "C4H9NO3", acidpKavalues = "2.037"},
                        new acids { acidname = "Threonine", acidformula = "C4H9NO3", acidpKavalues = "2.09,9.1"},
                        new acids { acidname = "Creatine", acidformula = "C4H9N3O2", acidpKavalues = "2.63,14.3"},
                        new acids { acidname = "Piperazine", acidformula = "C4H10N2", acidpKavalues = "9.83,5.56"},
                        new acids { acidname = "2,4-Diaminobutanoic acid", acidformula = "C4H10N2O2", acidpKavalues = "1.85,8.24,10.44"},
                        new acids { acidname = "Butylamine", acidformula = "C4H11N", acidpKavalues = "10.77"},
                        new acids { acidname = "sec-Butylamine", acidformula = "C4H11N", acidpKavalues = "10.56"},
                        new acids { acidname = "tert-Butylamine", acidformula = "C4H11N", acidpKavalues = "10.68"},
                        new acids { acidname = "Diethylamine", acidformula = "C4H11N", acidpKavalues = "11.02"},
                        new acids { acidname = "1,4-Butanediamine", acidformula = "C4H12N2", acidpKavalues = "10.8,9.35"},
                        new acids { acidname = "1,2-Dimethylaminoethane", acidformula = "C4H12O2", acidpKavalues = "10.4,8.26"},
                        new acids { acidname = "3-Bromopyridine", acidformula = "C5H4BrN", acidpKavalues = "2.84"},
                        new acids { acidname = "3-Chloropyridine", acidformula = "C5H4CIN", acidpKavalues = "2.84"},
                        new acids { acidname = "Purine", acidformula = "C5H4N4", acidpKavalues = "2.3,8.96"},
                        new acids { acidname = "Uric acid", acidformula = "C5H4N4O3", acidpKavalues = "3.89"},
                        new acids { acidname = "Pyridine", acidformula = "C5H5N", acidpKavalues = "5.25"},
                        new acids { acidname = "4-Pyridinol", acidformula = "C5H5NO", acidpKavalues = "3.2,11.12"},
                        new acids { acidname = "2(1H)-Pyridinone", acidformula = "C5H5NO", acidpKavalues = "0.75,11.65"},
                        new acids { acidname = "1H-Purin-6-amine", acidformula = "C5H5N5", acidpKavalues = "4.12,9.83"},
                        new acids { acidname = "2-Methylpyrazine", acidformula = "C5H6N2", acidpKavalues = "1.45"},
                        new acids { acidname = "2-Pyridinamine", acidformula = "C5H6N2", acidpKavalues = "6.82"},
                        new acids { acidname = "4-Pyridinamine", acidformula = "C5H6N2", acidpKavalues = "9.114"},
                        new acids { acidname = "1,1-Cyclopropanedicarboxylic acid", acidformula = "C5H6O4", acidpKavalues = "1.82,7.43"},
                        new acids { acidname = "Itaconic acid", acidformula = "C5H6O4", acidpKavalues = "3.85,5.45"},
                        new acids { acidname = "Mesaconic acid", acidformula = "C5H6O4", acidpKavalues = "3.09,4.75"},
                        new acids { acidname = "2-Oxoglutaric acid", acidformula = "C5H6O5", acidpKavalues = "2.47,4.68"},
                        new acids { acidname = "L-2-Pyrrolidone-5-carboxylic acid", acidformula = "C5H7NO3", acidpKavalues = "3.32"},
                        new acids { acidname = "Methylaminopyrazine", acidformula = "C5H7N3", acidpKavalues = "3.39"},
                        new acids { acidname = "2,5-Pyridinediamine", acidformula = "C5H7N3", acidpKavalues = "6.48"},
                        new acids { acidname = "2,4-Dimethylimidazzol", acidformula = "C5H8N2", acidpKavalues = "8.36"},
                        new acids { acidname = "Dimethylmalonic acid", acidformula = "C5H8O4", acidpKavalues = "3.15"},
                        new acids { acidname = "Glutaric acid", acidformula = "C5H8O4", acidpKavalues = "4.31,5.41"},
                        new acids { acidname = "Methylsuccinic acid", acidformula = "C5H8O4", acidpKavalues = "4.13,5.64"},
                        new acids { acidname = "Proline", acidformula = "C5H9NO2", acidpKavalues = "1.952,10.64"},
                        new acids { acidname = "5-Aminolevulinic acid", acidformula = "C5H9NO3", acidpKavalues = "4.05,8.9"},
                        new acids { acidname = "trans-4-Hydroxyroline", acidformula = "C5H9NO3", acidpKavalues = "1.818,9.662"},
                        new acids { acidname = "8-Hydroxypurine", acidformula = "C5H9NO3", acidpKavalues = "2.56,8.26"},
                        new acids { acidname = "L-Glutamic acid", acidformula = "C5H9NO4", acidpKavalues = "2.13,4.31"},
                        new acids { acidname = "Histamine", acidformula = "C5H9N3", acidpKavalues = "6.04,9.75"},
                        new acids { acidname = "L-Glutamine", acidformula = "C5H10N2O3", acidpKavalues = "2.17,9.13"},
                        new acids { acidname = "Glycylalanine", acidformula = "C5H10N2O3", acidpKavalues = "3.15"},
                        new acids { acidname = "Glycylserine", acidformula = "C5H10N2O4", acidpKavalues = "2.98,8.38"},
                        new acids { acidname = "2-Methylbutanoic acid", acidformula = "C5H10O2", acidpKavalues = "4.8"},
                        new acids { acidname = "3-Methylbutanoic acid", acidformula = "C5H10O2", acidpKavalues = "4.77"},
                        new acids { acidname = "Pentanoic acid", acidformula = "C5H10O2", acidpKavalues = "4.84"},
                        new acids { acidname = "Trimethylacetic acid  ", acidformula = "C5H10O2", acidpKavalues = "5.03"},
                        new acids { acidname = "N-Methylpyrrolidine", acidformula = "C5H11N", acidpKavalues = "10.32"},
                        new acids { acidname = "Piperidine", acidformula = "C5H11N", acidpKavalues = "11.123"},
                        new acids { acidname = "5-Aminopentanoic acid", acidformula = "C5H11NO2", acidpKavalues = "4.27,10.766"},
                        new acids { acidname = "Betaine", acidformula = "C5H11NO2", acidpKavalues = "1.83"},
                        new acids { acidname = "Norvaline", acidformula = "C5H11NO2", acidpKavalues = "2.32,9.81"},
                        new acids { acidname = "N-Propylglycine", acidformula = "C5H11NO2", acidpKavalues = "2.35,10.19"},
                        new acids { acidname = "Valine", acidformula = "C5H11NO2", acidpKavalues = "2.29,9.74"},
                        new acids { acidname = "Methionine", acidformula = "C5H11NO2S", acidpKavalues = "2.13,9.27"},
                        new acids { acidname = "Ornithine", acidformula = "C5H12N2O2", acidpKavalues = "1.705,8.69,10.76"},
                        new acids { acidname = "1-Aminno-2,2-dimethylpropane", acidformula = "C5H13N", acidpKavalues = "10.15"},
                        new acids { acidname = "Diethylmethylamine", acidformula = "C5H13N", acidpKavalues = "10.35"},
                        new acids { acidname = "3-Methyl-1-butanamine", acidformula = "C5H13N", acidpKavalues = "10.6"},
                        new acids { acidname = "2-Methyl 2-butanamine", acidformula = "C5H13N", acidpKavalues = "10.85"},
                        new acids { acidname = "3-Pentanamine", acidformula = "C5H13N", acidpKavalues = "10.59"},
                        new acids { acidname = "Pentylamine", acidformula = "C5H13N", acidpKavalues = "10.63"},
                        new acids { acidname = "Choline", acidformula = "C5H14NO", acidpKavalues = "13.9"},
                        new acids { acidname = "Cadaverine", acidformula = "C5H14N2", acidpKavalues = "10.05,10.93"},
                        new acids { acidname = "6-Cbloropteridine", acidformula = "C6H3CIN4", acidpKavalues = "3.68"},
                        new acids { acidname = "Picric acid", acidformula = "C6H3N3O7", acidpKavalues = "0.38"},
                        new acids { acidname = "2,3-Dichlorophenol", acidformula = "C6H4Cl2O", acidpKavalues = "7.44"},
                        new acids { acidname = "5-Hydroxylysine", acidformula = "C6H4N2O3", acidpKavalues = "2.13"},
                        new acids { acidname = "2,4-Dinitrophenol", acidformula = "C6H4N2O5", acidpKavalues = "3.96"},
                        new acids { acidname = "3,6-Dinitrophenol", acidformula = "C6H4N2O5", acidpKavalues = "5.15"},
                        new acids { acidname = "Pteridine", acidformula = "C6H4N4", acidpKavalues = "4.05"},
                        new acids { acidname = "3,5-Dibromoaniline", acidformula = "C6H5Br2N", acidpKavalues = "2.34"},
                        new acids { acidname = "2-Chlorophenol", acidformula = "C6H5CIO", acidpKavalues = "8.49"},
                        new acids { acidname = "3-Chlorophenol", acidformula = "C6H5CIO", acidpKavalues = "8.85"},
                        new acids { acidname = "4-Chlorophenol", acidformula = "C6H5CIO", acidpKavalues = "9.18"},
                        new acids { acidname = "2,4-Dichloroaniline", acidformula = "C6H5CI2N", acidpKavalues = "2.05"},
                        new acids { acidname = "2-Pyridinecarboxaldehyde", acidformula = "C6H5NO", acidpKavalues = "3.8"},
                        new acids { acidname = "Nitrobenzene", acidformula = "C6H5NO2", acidpKavalues = "3.98"},
                        new acids { acidname = "Picolinic acid", acidformula = "C6H5NO2", acidpKavalues = "1.07,5.25"},
                        new acids { acidname = "3-Pyridinecarboxylic acid", acidformula = "C6H5NO2", acidpKavalues = "4.85"},
                        new acids { acidname = "4-Pyridinecarboxylic acid", acidformula = "C6H5NO2", acidpKavalues = "4.96"},
                        new acids { acidname = "2-Nitrophenol", acidformula = "C6H5NO3", acidpKavalues = "7.17"},
                        new acids { acidname = "3-Nitrophenol", acidformula = "C6H5NO3", acidpKavalues = "8.28"},
                        new acids { acidname = "4-Nitrophenol", acidformula = "C6H5NO3", acidpKavalues = "7.15"},
                        new acids { acidname = "2-Amino-4-hydroxypteridine", acidformula = "C6H5N5O", acidpKavalues = "2.27,7.96,6.59,9.31"},
                        new acids { acidname = "2-Bromoaniline", acidformula = "C6H6BrN", acidpKavalues = "2.53"},
                        new acids { acidname = "3-Bromoaniline", acidformula = "C6H6BrN", acidpKavalues = "3.58"},
                        new acids { acidname = "4-Bromoaniline", acidformula = "C6H6BrN", acidpKavalues = "3.86"},
                        new acids { acidname = "2-Chloroaniline", acidformula = "C6H6CIN", acidpKavalues = "2.65"},
                        new acids { acidname = "3-Chloroaniline", acidformula = "C6H6CIN", acidpKavalues = "3.46"},
                        new acids { acidname = "4-Chloroaniline", acidformula = "C6H6CIN", acidpKavalues = "4.15"},
                        new acids { acidname = "2-Fluoroaniline", acidformula = "C6H6FN", acidpKavalues = "3.2"},
                        new acids { acidname = "3-Fluoroaniline", acidformula = "C6H6FN", acidpKavalues = "3.5"},
                        new acids { acidname = "4-Fluoroaniline", acidformula = "C6H6FN", acidpKavalues = "4.65"},
                        new acids { acidname = "2-Iodoaniline", acidformula = "C6H6IN", acidpKavalues = "2.6"},
                        new acids { acidname = "2-Pyridinecarboxaldehyde,oxime", acidformula = "C6H6N2O", acidpKavalues = "3.59,10.18"},
                        new acids { acidname = "2-Nitroaniline", acidformula = "C6H6N2O2", acidpKavalues = "-0.26"},
                        new acids { acidname = "3-Nitroaniline", acidformula = "C6H6N2O2", acidpKavalues = "2.466"},
                        new acids { acidname = "4-Nitroaniline", acidformula = "C6H6N2O2", acidpKavalues = "1"},
                        new acids { acidname = "Phenol", acidformula = "C6H6O", acidpKavalues = "9.89"},
                        new acids { acidname = "Hydroquinone", acidformula = "C6H6O2", acidpKavalues = "10.35"},
                        new acids { acidname = "Pyrocatechol", acidformula = "C6H6O2", acidpKavalues = "9.85"},
                        new acids { acidname = "Resorcinol", acidformula = "C6H6O2", acidpKavalues = "9.81"},
                        new acids { acidname = "Benzenesulfonic acid", acidformula = "C6H6O3S", acidpKavalues = "0.7"},
                        new acids { acidname = "cis-Aconitic acid", acidformula = "C6H6O6", acidpKavalues = "1.95"},
                        new acids { acidname = "trans-Aconitic acid", acidformula = "C6H6O6", acidpKavalues = "2.8,4.46"},
                        new acids { acidname = "Aniline", acidformula = "C6H7N", acidpKavalues = "4.63"},
                        new acids { acidname = "2-Methylpyridine", acidformula = "C6H7N", acidpKavalues = "5.97"},
                        new acids { acidname = "3-Methylpyridine", acidformula = "C6H7N", acidpKavalues = "5.68"},
                        new acids { acidname = "4-Methylpyridine", acidformula = "C6H7N", acidpKavalues = "6.02"},
                        new acids { acidname = "Methoxypyridine", acidformula = "C6H7NO", acidpKavalues = "6.47"},
                        new acids { acidname = "o-Aminobenzenesulfonic acid", acidformula = "C6H7NO3S", acidpKavalues = "2.48"},
                        new acids { acidname = "m-Aminobenzenesulfonic acid", acidformula = "C6H7NO3S", acidpKavalues = "3.73"},
                        new acids { acidname = "p-Aminobenzenesulfonic acid", acidformula = "C6H7NO3S", acidpKavalues = "3.24"},
                        new acids { acidname = "N-Methylpyridinamine", acidformula = "C6H8N2", acidpKavalues = "9.65"},
                        new acids { acidname = "Ascorbic acid", acidformula = "C6H8O6", acidpKavalues = "4.1,11.79"},
                        new acids { acidname = "Citric acid", acidformula = "C6H8O7", acidpKavalues = "3.14,4.77,6.39"},
                        new acids { acidname = "Isocitric acid", acidformula = "C6H8O7", acidpKavalues = "3.29,4.71,6.4"},
                        new acids { acidname = "g-Carboxyglutamic acid", acidformula = "C6H9NO6", acidpKavalues = "1.7,3.2,4.75,9.9"},
                        new acids { acidname = "4,6-Dimethylpyrimidinamine", acidformula = "C6H9N3", acidpKavalues = "4.82"},
                        new acids { acidname = "Histidine", acidformula = "C6H9N3O2", acidpKavalues = "1.8,6.04,9.33"},
                        new acids { acidname = "2-Oxo-3-methylpentanoic acid", acidformula = "C6H10O3", acidpKavalues = "2.3"},
                        new acids { acidname = "Adipic acid", acidformula = "C6H10O4", acidpKavalues = "4.43,5.41"},
                        new acids { acidname = "3-Methylglutaric acid", acidformula = "C6H10O4", acidpKavalues = "4.24"},
                        new acids { acidname = "l-Pipecolic acid", acidformula = "C6H11NO2", acidpKavalues = "2.28,10.72"},
                        new acids { acidname = "Adiparnic acid", acidformula = "C6H11NO3", acidpKavalues = "4.63"},
                        new acids { acidname = "2-Aminoadipic macid", acidformula = "C6H11NO4", acidpKavalues = "2.14,4.21,9.77"},
                        new acids { acidname = "Glycylasparagine", acidformula = "C6H11N3O4", acidpKavalues = "2.942,8.44"},
                        new acids { acidname = "N-(N-Glycylglycyl)glycine", acidformula = "C6H11N3O4", acidpKavalues = "3.225,8.09"},
                        new acids { acidname = "Cystine", acidformula = "C6H12N2O4S2", acidpKavalues = "2.1,8"},
                        new acids { acidname = "Hexanoic acid", acidformula = "C6H12O2", acidpKavalues = "4.85"},
                        new acids { acidname = "4-Methylpentanoic acid", acidformula = "C6H12O2", acidpKavalues = "4.84"},
                        new acids { acidname = "Cyclohexylamine", acidformula = "C6H13N", acidpKavalues = "10.66"},
                        new acids { acidname = "1,2-Dimethylpyrrolidine", acidformula = "C6H13N", acidpKavalues = "10.2"},
                        new acids { acidname = "1-Methylpiperidine", acidformula = "C6H13N", acidpKavalues = "10.08"},
                        new acids { acidname = "6-Aminohexanoic acid", acidformula = "C6H13NO2", acidpKavalues = "4.373,10.804"},
                        new acids { acidname = "Isoleucine", acidformula = "C6H13NO2", acidpKavalues = "2.32,9.76"},
                        new acids { acidname = "L-Leucine", acidformula = "C6H13NO2", acidpKavalues = "2.328,9.744"},
                        new acids { acidname = "Norleucine", acidformula = "C6H13NO2", acidpKavalues = "2.335,9.83"},
                        new acids { acidname = "Citrulline", acidformula = "C6H13N3O3", acidpKavalues = "2.43,9.69"},
                        new acids { acidname = "cis-1,2-Cyclohexanediamine", acidformula = "C6H14N2", acidpKavalues = "9.93,6.13"},
                        new acids { acidname = "trans-1,2-Cyclohexanediamine", acidformula = "C6H14N2", acidpKavalues = "9.94,6.47"},
                        new acids { acidname = "2,5-Dimethylpiperazine", acidformula = "C6H14N2", acidpKavalues = "9.66,5.2"},
                        new acids { acidname = "Lysine", acidformula = "C6H14N2O2", acidpKavalues = "2.16,9.06,10.54"},
                        new acids { acidname = "Arginine", acidformula = "C6H14N4O2", acidpKavalues = "1.82,8.99,12.48"},
                        new acids { acidname = "3-Amino-3-methylpentane", acidformula = "C6H15N", acidpKavalues = "11.01"},
                        new acids { acidname = "Diisopropylamine", acidformula = "C6H15N", acidpKavalues = "11.05"},
                        new acids { acidname = "Hexylamine", acidformula = "C6H15N", acidpKavalues = "10.56"},
                        new acids { acidname = "Triethylamine", acidformula = "C6H15N", acidpKavalues = "10.75"},
                        new acids { acidname = "Hexamethylenediamine", acidformula = "C6H16N2", acidpKavalues = "11.857,10.762"},
                        new acids { acidname = "2-Bromobenzoic acid", acidformula = "C7H5BrO2", acidpKavalues = "2.84"},
                        new acids { acidname = "3-Bromobenzoic acid", acidformula = "C7H5BrO2", acidpKavalues = "3.86"},
                        new acids { acidname = "2-Chlorobenzoic acid", acidformula = "C7H5CIO2", acidpKavalues = "2.92"},
                        new acids { acidname = "3-Chlorobenzoic acid", acidformula = "C7H5CIO2", acidpKavalues = "3.82"},
                        new acids { acidname = "4-Chlorobenzoic acid", acidformula = "C7H5CIO2", acidpKavalues = "3.98"},
                        new acids { acidname = "2-Iodobenzoic acid", acidformula = "C7H5IO2", acidpKavalues = "2.85"},
                        new acids { acidname = "3-Iodobenzoic acid", acidformula = "C7H5IO2", acidpKavalues = "3.8"},
                        new acids { acidname = "Saccharin", acidformula = "C7H5NO3S", acidpKavalues = "11.68"},
                        new acids { acidname = "Dinicotinic acid", acidformula = "C7H5NO4", acidpKavalues = "2.8"},
                        new acids { acidname = "Dipicolinic acid", acidformula = "C7H5NO4", acidpKavalues = "2.16,4.76"},
                        new acids { acidname = "Lutidinic acid", acidformula = "C7H5NO4", acidpKavalues = "2.15"},
                        new acids { acidname = "2-Nitrobenzoic acid", acidformula = "C7H5NO4", acidpKavalues = "2.16"},
                        new acids { acidname = "3-Nitrobenzoic acid", acidformula = "C7H5NO4", acidpKavalues = "3.47"},
                        new acids { acidname = "4-Nitrobenzoic acid", acidformula = "C7H5NO4", acidpKavalues = "3.41"},
                        new acids { acidname = "Quinolinic acid", acidformula = "C7H5NO4", acidpKavalues = "2.43,4.78"},
                        new acids { acidname = "Benzimidazole", acidformula = "C7H6N2", acidpKavalues = "5.532"},
                        new acids { acidname = "6-Hydroxy-4-methylpteridine", acidformula = "C7H6N4O", acidpKavalues = "4.08,6.41"},
                        new acids { acidname = "Benzoic acid", acidformula = "C7H6O2", acidpKavalues = "4.19"},
                        new acids { acidname = "o-Hydroxy-4-methylpteridine", acidformula = "C7H6O3", acidpKavalues = "2.97,13.4"},
                        new acids { acidname = "m-Hydroxybenzoic acid", acidformula = "C7H6O3", acidpKavalues = "4.06,9.92"},
                        new acids { acidname = "p-Hydroxybenzoic acid", acidformula = "C7H6O3", acidpKavalues = "4.48,9.32"},
                        new acids { acidname = "2,5-Dihydroxybenzoic acid", acidformula = "C7H6O4", acidpKavalues = "2.97"},
                        new acids { acidname = "3,4-Dihydroxybenzoic acid", acidformula = "C7H6O4", acidpKavalues = "4.48,8.83,12.6"},
                        new acids { acidname = "3,5-Dihydroxybenzoic acid", acidformula = "C7H6O4", acidpKavalues = "4.04"},
                        new acids { acidname = "Dihydroxymalic acid", acidformula = "C7H6O4", acidpKavalues = "1.92"},
                        new acids { acidname = "Gallic acid", acidformula = "C7H6O5", acidpKavalues = "4.41"},
                        new acids { acidname = "2,4,6-Trihydroxybenzoic acid", acidformula = "C7H6O5", acidpKavalues = "1.68"},
                        new acids { acidname = "2-Aminobenzoic acid", acidformula = "C7H7NO2", acidpKavalues = "2.108,4.946,4.78"},
                        new acids { acidname = "4-Animobenzoic acid", acidformula = "C7H7NO2", acidpKavalues = "2.501,4.874"},
                        new acids { acidname = "Theobromine", acidformula = "C7H8N4O2", acidpKavalues = "7.89"},
                        new acids { acidname = "o-Cresol", acidformula = "C7H8O", acidpKavalues = "10.2"},
                        new acids { acidname = "m-Cresol", acidformula = "C7H8O", acidpKavalues = "10.01"},
                        new acids { acidname = "p-Cresol", acidformula = "C7H8O", acidpKavalues = "10.17"},
                        new acids { acidname = "Benzylamine", acidformula = "C7H9N", acidpKavalues = "9.33"},
                        new acids { acidname = "2,3-Dimethylpyridine", acidformula = "C7H9N", acidpKavalues = "6.57"},
                        new acids { acidname = "2,4-Dimethylpyridine", acidformula = "C7H9N", acidpKavalues = "6.99"},
                        new acids { acidname = "2,5-Dimethylpyridine", acidformula = "C7H9N", acidpKavalues = "6.4"},
                        new acids { acidname = "2,6-Dimethylpyridine", acidformula = "C7H9N", acidpKavalues = "6.65"},
                        new acids { acidname = "3,4-Dimethylpyridine", acidformula = "C7H9N", acidpKavalues = "6.46"},
                        new acids { acidname = "3,5-Dimethylpyridine", acidformula = "C7H9N", acidpKavalues = "6.15"},
                        new acids { acidname = "2-Ethylpyridine", acidformula = "C7H9N", acidpKavalues = "5.89"},
                        new acids { acidname = "N-Methylaniline", acidformula = "C7H9N", acidpKavalues = "4.84"},
                        new acids { acidname = "o-Methylaniline", acidformula = "C7H9N", acidpKavalues = "4.44"},
                        new acids { acidname = "m-Methylaniline", acidformula = "C7H9N", acidpKavalues = "4.73"},
                        new acids { acidname = "p-Methylaniline", acidformula = "C7H9N", acidpKavalues = "5.08"},
                        new acids { acidname = "o-Anisidine", acidformula = "C7H9NO", acidpKavalues = "4.52"},
                        new acids { acidname = "m-Anisidine", acidformula = "C7H9NO", acidpKavalues = "4.23"},
                        new acids { acidname = "p-Anisidine", acidformula = "C7H9NO", acidpKavalues = "5.34"},
                        new acids { acidname = "4-Methylthioaniline", acidformula = "C7H9NS", acidpKavalues = "4.35"},
                        new acids { acidname = "2-Dimethylaminopurine", acidformula = "C7H9N5", acidpKavalues = "4,10.24"},
                        new acids { acidname = "l-1-Methylhistidine", acidformula = "C7H11N3O2", acidpKavalues = "1.69,6.48,8.85"},
                        new acids { acidname = "l-3-Methylhistidine", acidformula = "C7H11N3O2", acidpKavalues = "1.92,6.56,8.73"},
                        new acids { acidname = "Cyclohexanecarboxylic acid", acidformula = "C7H12O2", acidpKavalues = "4.9"},
                        new acids { acidname = "Heptanedioic acid", acidformula = "C7H12O4", acidpKavalues = "4.71,5.58"},
                        new acids { acidname = "3-Acetylpiperidine", acidformula = "C7H13NO", acidpKavalues = "3.18"},
                        new acids { acidname = "a-Ethylglutamic acid", acidformula = "C7H13NO4", acidpKavalues = "3.846,7.838"},
                        new acids { acidname = "Heptanoic acid", acidformula = "C7H14O2", acidpKavalues = "4.89"},
                        new acids { acidname = "1,2-Dimethylpiperidine", acidformula = "C7H15N", acidpKavalues = "10.22"},
                        new acids { acidname = "1-Ethylpiperidine", acidformula = "C7H15N", acidpKavalues = "10.45"},
                        new acids { acidname = "Carnitine", acidformula = "C7H15NO3", acidpKavalues = "3.8"},
                        new acids { acidname = "2-Heptanamine", acidformula = "C7H17N", acidpKavalues = "10.7"},
                        new acids { acidname = "Heptylamine", acidformula = "C7H17N", acidpKavalues = "10.67"},
                        new acids { acidname = "Cinnoline", acidformula = "C8H6N2", acidpKavalues = "2.37"},
                        new acids { acidname = "Quinazoline", acidformula = "C8H6N2", acidpKavalues = "3.43"},
                        new acids { acidname = "Quinoxaline", acidformula = "C8H6N2", acidpKavalues = "0.56"},
                        new acids { acidname = "5-Hydoxxyquinazoline", acidformula = "C8H6N2O", acidpKavalues = "3.62,7.41"},
                        new acids { acidname = "o-Phthalic acid", acidformula = "C8H6O4", acidpKavalues = "2.89,5.51"},
                        new acids { acidname = "m-Phthalic acid", acidformula = "C8H6O4", acidpKavalues = "3.54,4.6"},
                        new acids { acidname = "p-Phthalic acid", acidformula = "C8H6O4", acidpKavalues = "3.51,4.82"},
                        new acids { acidname = "Terephthalic acid", acidformula = "C8H6O4", acidpKavalues = "3.51"},
                        new acids { acidname = "2-Chlorophenylacetic acid", acidformula = "C8H7CIO2", acidpKavalues = "4.07"},
                        new acids { acidname = "3-Chlorophenylacetic acid", acidformula = "C8H7CIO2", acidpKavalues = "4.14"},
                        new acids { acidname = "4-Chlorophenylacetic acid", acidformula = "C8H7CIO2", acidpKavalues = "4.19"},
                        new acids { acidname = "2-Chlorophenoxyacetic acid", acidformula = "C8H7CIO3", acidpKavalues = "3.05"},
                        new acids { acidname = "3-Chlorophenoxyacetic acid", acidformula = "C8H7CIO3", acidpKavalues = "3.1"},
                        new acids { acidname = "2-Nitrophenylacetic acid", acidformula = "C8H7NO4", acidpKavalues = "4"},
                        new acids { acidname = "3-Nitrophenylacetic acid", acidformula = "C8H7NO4", acidpKavalues = "3.97"},
                        new acids { acidname = "4-Nitrophenylacetic acid", acidformula = "C8H7NO4", acidpKavalues = "3.85"},
                        new acids { acidname = "2-Methylbenzimidazole", acidformula = "C8H8N2", acidpKavalues = "6.19"},
                        new acids { acidname = "Phenylacetic acid", acidformula = "C8H8O2", acidpKavalues = "4.28"},
                        new acids { acidname = "o-Toluic acid", acidformula = "C8H8O2", acidpKavalues = "3.91"},
                        new acids { acidname = "m-Toluic acid", acidformula = "C8H8O2", acidpKavalues = "4.27"},
                        new acids { acidname = "p-Toluic acid", acidformula = "C8H8O2", acidpKavalues = "4.36"},
                        new acids { acidname = "DL-Mandelic acid", acidformula = "C8H8O3", acidpKavalues = "3.85"},
                        new acids { acidname = "Homogentisic acid", acidformula = "C8H8O4", acidpKavalues = "4.4"},
                        new acids { acidname = "2-(Methylamino)benzoic acid", acidformula = "C8H9NO2", acidpKavalues = "5.34"},
                        new acids { acidname = "3-(Methylamino)benzoic acid", acidformula = "C8H9NO2", acidpKavalues = "5.1"},
                        new acids { acidname = "4-(Methylamino)benzoic acid", acidformula = "C8H9NO2", acidpKavalues = "5.04"},
                        new acids { acidname = "Phenylglycine", acidformula = "C8H9NO2", acidpKavalues = "1.83,4.39"},
                        new acids { acidname = "4-Bromo-N,N-dimethylaniline", acidformula = "C8H10BrN", acidpKavalues = "4.23"},
                        new acids { acidname = "3-Chloro-N,N-dimethylaniline", acidformula = "C8H10CIN", acidpKavalues = "3.83"},
                        new acids { acidname = "4-Chloro-N,N-dimethylaniline", acidformula = "C8H10CIN", acidpKavalues = "4.39"},
                        new acids { acidname = "N,N-Dimethyl-3-nitroaniline", acidformula = "C8H10N2O2", acidpKavalues = "2.62"},
                        new acids { acidname = "N,N-Dimethylaniline", acidformula = "C8H11N", acidpKavalues = "5.15"},
                        new acids { acidname = "N-Ethylaniline", acidformula = "C8H11N", acidpKavalues = "5.12"},
                        new acids { acidname = "Phenylethylamine", acidformula = "C8H11N", acidpKavalues = "9.84"},
                        new acids { acidname = "2,4,6-Trimethylpyridine", acidformula = "C8H11N", acidpKavalues = "7.43"},
                        new acids { acidname = "o-Phenetidine", acidformula = "C8H11NO", acidpKavalues = "4.43"},
                        new acids { acidname = "m-Phenetidine", acidformula = "C8H11NO", acidpKavalues = "4.18"},
                        new acids { acidname = "p-Phenetidine", acidformula = "C8H11NO", acidpKavalues = "5.2"},
                        new acids { acidname = "Tyramine", acidformula = "C8H11NO", acidpKavalues = "9.74,10.52"},
                        new acids { acidname = "Dopamine", acidformula = "C8H11NO2", acidpKavalues = "8.9,10.6"},
                        new acids { acidname = "Noradrenaline", acidformula = "C8H11NO3", acidpKavalues = "8.64,9.7"},
                        new acids { acidname = "Veronal", acidformula = "C8H12N2O3", acidpKavalues = "7.43"},
                        new acids { acidname = "Octanedioic acid", acidformula = "C8H14O4", acidpKavalues = "4.52"},
                        new acids { acidname = "N-Glycylleucine", acidformula = "C8H16N2O3", acidpKavalues = "3.18"},
                        new acids { acidname = "N-Leucylglycine", acidformula = "C8H16N2O3", acidpKavalues = "3.25,8.2"},
                        new acids { acidname = "Homocystine", acidformula = "C8H16N2O4S2", acidpKavalues = "1.59,2.54,8.52,9.44"},
                        new acids { acidname = "Octanoic acid", acidformula = "C8H16O2", acidpKavalues = "4.89"},
                        new acids { acidname = "2,2,4-Trimethylpiperidine", acidformula = "C8H17N", acidpKavalues = "11.04"},
                        new acids { acidname = "Dibutylamine", acidformula = "C8H19N", acidpKavalues = "11.25"},
                        new acids { acidname = "N-Methyl-2-heptanamine", acidformula = "C8H19N", acidpKavalues = "10.99"},
                        new acids { acidname = "Octylamine", acidformula = "C8H19N", acidpKavalues = "10.65"},
                        new acids { acidname = "3-Bromoquinoline", acidformula = "C9H6BrN", acidpKavalues = "2.69"},
                        new acids { acidname = "o-Chlorocinnamic acid", acidformula = "C9H7CIO2", acidpKavalues = "4.23"},
                        new acids { acidname = "m-Chlorocinnamic acid", acidformula = "C9H7CIO2", acidpKavalues = "4.29"},
                        new acids { acidname = "p-Chlorocinnamic acid", acidformula = "C9H7CIO2", acidpKavalues = "4.41"},
                        new acids { acidname = "Isoquinoline", acidformula = "C9H7N", acidpKavalues = "5.42"},
                        new acids { acidname = "Quinoline", acidformula = "C9H7N", acidpKavalues = "4.9"},
                        new acids { acidname = "7-Isoquinolinol", acidformula = "C9H7NO", acidpKavalues = "5.68,8.9"},
                        new acids { acidname = "3-Quinolinol", acidformula = "C9H7NO", acidpKavalues = "4.28,8.08"},
                        new acids { acidname = "8-Quinolinol", acidformula = "C9H7NO", acidpKavalues = "5.017,9.812"},
                        new acids { acidname = "o-Cyanophenoxyacetic acid", acidformula = "C9H7NO3", acidpKavalues = "2.98"},
                        new acids { acidname = "m-Cyanophenoxyacetic acid", acidformula = "C9H7NO3", acidpKavalues = "3.03"},
                        new acids { acidname = "p-Cyanophenoxyacetic acid", acidformula = "C9H7NO3", acidpKavalues = "2.93"},
                        new acids { acidname = "1-Isoquinolinamine", acidformula = "C9H8N2", acidpKavalues = "7.59"},
                        new acids { acidname = "3-Quinolinamine", acidformula = "C9H8N2", acidpKavalues = "4.91"},
                        new acids { acidname = "cis-Cinnamic acid", acidformula = "C9H8O2", acidpKavalues = "3.89"},
                        new acids { acidname = "trans-Cinnamic acid", acidformula = "C9H8O2", acidpKavalues = "4.44"},
                        new acids { acidname = "3-(2-Chlorophenyl)propanoic acid", acidformula = "C9H9CIO2", acidpKavalues = "4.58"},
                        new acids { acidname = "3-(3-Chlorophenyl)propanoic acid", acidformula = "C9H9CIO2", acidpKavalues = "4.59"},
                        new acids { acidname = "3-(4-Chlorophenyl)propanoic acid", acidformula = "C9H9CIO2", acidpKavalues = "4.61"},
                        new acids { acidname = "3,5-Diiodityrosine", acidformula = "C9H9I2NO3", acidpKavalues = "2.12,5.32,9.48"},
                        new acids { acidname = "Hippuric acid", acidformula = "C9H9NO3", acidpKavalues = "3.62"},
                        new acids { acidname = "3-(2-Nitrophenyl)propanoic acid", acidformula = "C9H9NO4", acidpKavalues = "4.5"},
                        new acids { acidname = "3-(4-Nitrophenyl)propanoic acid", acidformula = "C9H9NO4", acidpKavalues = "4.47"},
                        new acids { acidname = "3-Iodotyrosine", acidformula = "C9H10INO3", acidpKavalues = "2.2,8.7,9.1"},
                        new acids { acidname = "2-Ethylbenzimidazole", acidformula = "C9H10N2", acidpKavalues = "6.18"},
                        new acids { acidname = "Mesitylenic acid", acidformula = "C9H10O2", acidpKavalues = "4.32"},
                        new acids { acidname = "a-Phenylpropanoic acid", acidformula = "C9H10O2", acidpKavalues = "4.64"},
                        new acids { acidname = "b-Phenylpropanoic acid", acidformula = "C9H10O2", acidpKavalues = "4.37"},
                        new acids { acidname = "N-Allylaniline", acidformula = "C9H11N", acidpKavalues = "4.17"},
                        new acids { acidname = "1-Aminoindane", acidformula = "C9H11N", acidpKavalues = "9.21"},
                        new acids { acidname = "Phenylalanine", acidformula = "C9H11NO2", acidpKavalues = "2.2,9.31"},
                        new acids { acidname = "Tyrosine", acidformula = "C9H11NO3", acidpKavalues = "2.2,9.21,10.46"},
                        new acids { acidname = "L-3,4-Dihydroxyphenylalanine", acidformula = "C9H11NO4", acidpKavalues = "2.32,8.72,9.96,11.79"},
                        new acids { acidname = "Tyrosineamide", acidformula = "C9H12N2O2", acidpKavalues = "7.33"},
                        new acids { acidname = "D-Adrenaline", acidformula = "C9H13NO3", acidpKavalues = "8.66,9.95"},
                        new acids { acidname = "N-b-Alanylhistidine", acidformula = "C9H14N4O3", acidpKavalues = "2.73,6.87,9.73"},
                        new acids { acidname = "L-Carnosine", acidformula = "C9H14N4O3", acidpKavalues = "2.62,6.66,9.24"},
                        new acids { acidname = "Nonanic acid", acidformula = "C9H18O2", acidpKavalues = "4.96"},
                        new acids { acidname = "1-Butylpiperidine", acidformula = "C9H19N", acidpKavalues = "10.47"},
                        new acids { acidname = "2,2,6,6-Tetramethylpiperidine", acidformula = "C9H19N", acidpKavalues = "11.07"},
                        new acids { acidname = "Nonylamine", acidformula = "C9H21N", acidpKavalues = "10.64"},
                        new acids { acidname = "8-Quinolinecarboxylic acid", acidformula = "C10H7NO2", acidpKavalues = "1.82"},
                        new acids { acidname = "1-Naphthol", acidformula = "C10H8O", acidpKavalues = "9.34"},
                        new acids { acidname = "2-Naphthol", acidformula = "C10H8O", acidpKavalues = "9.51"},
                        new acids { acidname = "2-Methylquinoline", acidformula = "C10H9N", acidpKavalues = "5.83"},
                        new acids { acidname = "4-Methylquinoline", acidformula = "C10H9N", acidpKavalues = "5.67"},
                        new acids { acidname = "5-Methylquinoline", acidformula = "C10H9N", acidpKavalues = "5.2"},
                        new acids { acidname = "a-Naphthylamine", acidformula = "C10H9N", acidpKavalues = "3.92"},
                        new acids { acidname = "b-Naphthylamine", acidformula = "C10H9N", acidpKavalues = "4.16"},
                        new acids { acidname = "1-Amino-6-hydroxynaphthalene", acidformula = "C10H9NO", acidpKavalues = "3.97"},
                        new acids { acidname = "6-Methoxyquinoline", acidformula = "C10H9NO", acidpKavalues = "5.03"},
                        new acids { acidname = "o-Methylcinnamic acid", acidformula = "C10H10O2", acidpKavalues = "4.5"},
                        new acids { acidname = "m-Methylcinnamic acid", acidformula = "C10H10O2", acidpKavalues = "4.44"},
                        new acids { acidname = "p-Methylcinnamic acid", acidformula = "C10H10O2", acidpKavalues = "4.56"},
                        new acids { acidname = "Tryptamine", acidformula = "C10H12N2", acidpKavalues = "10.2"},
                        new acids { acidname = "5-Hydroxytryptamine", acidformula = "C10H12N2O", acidpKavalues = "9.8,11.1"},
                        new acids { acidname = "4-Phenylbutanoic acid", acidformula = "C10H12O2", acidpKavalues = "4.76"},
                        new acids { acidname = "2-(m-Anisyl)propanoic acid", acidformula = "C10H12O3", acidpKavalues = "4.65"},
                        new acids { acidname = "2-(p-Anisyl)propanoic acid", acidformula = "C10H12O3", acidpKavalues = "4.69"},
                        new acids { acidname = "2-(o-Anisyl)propanoic acid", acidformula = "C10H12O3", acidpKavalues = "4.8"},
                        new acids { acidname = "Nicotine", acidformula = "C10H14N2", acidpKavalues = "8.02,3.12"},
                        new acids { acidname = "N,N-Diethylaniline", acidformula = "C10H15N", acidpKavalues = "6.61"},
                        new acids { acidname = "d-Ephedrine", acidformula = "C10H15NO", acidpKavalues = "10.139"},
                        new acids { acidname = "l-Ephedrine", acidformula = "C10H15NO", acidpKavalues = "9.958"},
                        new acids { acidname = "l-Glutathione", acidformula = "C10H17N3O6S", acidpKavalues = "2.12,3.59,8.75,9.65"},
                        new acids { acidname = "Tetraglycylglycine", acidformula = "C10H17N5O6", acidpKavalues = "3.1,8.02"},
                        new acids { acidname = "L-Argininosuccinic acid", acidformula = "C10H18N4O5", acidpKavalues = "1.62,2.7,4.26,9.58"},
                        new acids { acidname = "Bornylamine", acidformula = "C10H19N", acidpKavalues = "10.17"},
                        new acids { acidname = "Neobornylamine", acidformula = "C10H19N", acidpKavalues = "10.01"},
                        new acids { acidname = "Butylcyclohexylamine", acidformula = "C10H21N", acidpKavalues = "11.23"},
                        new acids { acidname = "Decylamine", acidformula = "C10H23N", acidpKavalues = "10.64"},
                        new acids { acidname = "Perimidine", acidformula = "C11H8N2", acidpKavalues = "6.35"},
                        new acids { acidname = "1-Naphthoic acid", acidformula = "C11H8O2", acidpKavalues = "3.7"},
                        new acids { acidname = "2-Naphthoic acid", acidformula = "C11H8O2", acidpKavalues = "4.17"},
                        new acids { acidname = "Methyl-1-naphthylamine", acidformula = "C11H11N", acidpKavalues = "3.67"},
                        new acids { acidname = "Tryptophan", acidformula = "C11H12N2O2", acidpKavalues = "2.46,9.41"},
                        new acids { acidname = "Pilocarpine", acidformula = "C11H16N2O2", acidpKavalues = "6.87"},
                        new acids { acidname = "Undecylamine", acidformula = "C11H25N", acidpKavalues = "10.63"},
                        new acids { acidname = "1,10-Phenanthroline", acidformula = "C12H8N2", acidpKavalues = "4.84"},
                        new acids { acidname = "2-Aminobiphenyl", acidformula = "C12H11N", acidpKavalues = "3.82"},
                        new acids { acidname = "2-Benzylpyridine", acidformula = "C12H11N", acidpKavalues = "5.13"},
                        new acids { acidname = "Diphenylamine", acidformula = "C12H11N", acidpKavalues = "0.79"},
                        new acids { acidname = "4-Aminoazobenzene", acidformula = "C12H11N3", acidpKavalues = "2.82"},
                        new acids { acidname = "p-Benzidine", acidformula = "C12H12N2", acidpKavalues = "4.66,3.57"},
                        new acids { acidname = "N,N-Dimethyl-1-naphthylamine", acidformula = "C12H13N", acidpKavalues = "4.83"},
                        new acids { acidname = "N,N-Dimethyl-2-naphthylamine", acidformula = "C12H13N", acidpKavalues = "4.566"},
                        new acids { acidname = "Dodecylamine", acidformula = "C12H27N", acidpKavalues = "10.63"},
                        new acids { acidname = "Acridine", acidformula = "C13H9N", acidpKavalues = "5.58"},
                        new acids { acidname = "Phenanthridine", acidformula = "C13H9N", acidpKavalues = "5.58"},
                        new acids { acidname = "2-Phenylbenzimidazole", acidformula = "C13H10N2", acidpKavalues = "5.23,11.91"},
                        new acids { acidname = "2-Phenylbenzoic acid", acidformula = "C13H10O2", acidpKavalues = "3.46"},
                        new acids { acidname = "4-(p-Aminobenzoyl)aniline", acidformula = "C13H12N2O", acidpKavalues = "2.93"},
                        new acids { acidname = "4-Benzylaniline", acidformula = "C13H13N", acidpKavalues = "2.17"},
                        new acids { acidname = "Tridecylamine", acidformula = "C13H29N", acidpKavalues = "10.63"},
                        new acids { acidname = "Diphenylacetic acid", acidformula = "C14H12O2", acidpKavalues = "3.94"},
                        new acids { acidname = "4-Dimethylaminoazobenzene", acidformula = "C14H15N3", acidpKavalues = "3.226"},
                        new acids { acidname = "Tetradecylamine", acidformula = "C14H31N", acidpKavalues = "10.62"},
                        new acids { acidname = "L-Thyroxine", acidformula = "C15H11I4NO4", acidpKavalues = "2.2,6.45,10.1"},
                        new acids { acidname = "Pentadecylamine", acidformula = "C15H33N", acidpKavalues = "10.61"},
                        new acids { acidname = "Hexadecylamine", acidformula = "C16H35N", acidpKavalues = "10.63"},
                        new acids { acidname = "Morphine", acidformula = "C17H19NO3", acidpKavalues = "8.21"},
                        new acids { acidname = "Codeine", acidformula = "C18H21NO3", acidpKavalues = "8.21"},
                        new acids { acidname = "Octadecylamine", acidformula = "C18H39N", acidpKavalues = "10.6"},
                        new acids { acidname = "Papaverine", acidformula = "C20H21NO4", acidpKavalues = "6.4"},
                        new acids { acidname = "Quinine", acidformula = "C20H24N2O2", acidpKavalues = "8.52,4.13"},
                        new acids { acidname = "Strychnine", acidformula = "C21H22N2O2", acidpKavalues = "8.26"},
                        new acids { acidname = "Brucine", acidformula = "C23H26N2O4", acidpKavalues = "8.28"},};

                   
                        var acidfinder = acid.FindAll(a => a.acidformula == acidlookup);

                        titrationdatastorage.acidfind.Clear();
                        titrationdatastorage.acidpkavalues.Clear();

                        if (acidfinder.Count > 1)
                        {

                            foreach (var acidinfo in acidfinder)
                            {
                                titrationdatastorage.acidfind.Add(acidinfo.acidname);
                                titrationdatastorage.acidpkavalues.Add(acidinfo.acidpKavalues);
                                titrationdatastorage.issingleacid = false;
                            }
                        }
                        else if (acidfinder.Count == 1)
                        {
                            titrationdatastorage.acidchosenpka = acidfinder[0].acidpKavalues;
                            titrationdatastorage.issingleacid = true;
                        }
                    
                }
            }

        }
    }
}
